### ISSUE TITLE
Error hit when syncing GH repo which contains comment with more than 100000 characters

### ISSUE THREAD

**Issue by tplevko** [release-engineering/Sync2Jira#123]
I hit this issue with this GH issue's comment - https://github.com/apache/camel-quarkus/issues/2957#issue-955186387, with more than 180K characters

it's first comment, so it was supposed to be used as a description in the Jira issue - this doesn't work, as the Jira API description limit is 1000000 characters.

Could this be limited on the sync2jira side?

**Comment by tplevko** [comment]
Edit: seems like the limit is 65,534 characters:

```response text = {"errorMessages":[],"errors":{"description":"The entered text is too long. It exceeds the allowed limit of 65,534 characters."}}```

**Comment by tplevko** [comment]
@sidpremkumar could you please have a look?

**Comment by tplevko** [comment]
@sidpremkumar sounds great! I'll ask someone if this can be tested - I don't have access to the deployment myself.

**Comment by sidpremkumar** [comment]
I've created this could you take a look: https://github.com/release-engineering/Sync2Jira/pull/124

**Comment by sidpremkumar** [comment]
Believe this issue can be closed now?

**Comment by qgong** [comment]
Close it.

**Comment by tplevko** [comment]
Seems like the fix didn't prevent the issue from happening - I can still see the error from the first comment in the pod logs. Do you maybe have an idea why the patch didn't solve the issue?

**Comment by sidpremkumar** [comment]
@tplevko , just to confirm how do we know it's coming from a comment?

**Comment by tplevko** [comment]
@sidpremkumar placing the full error log: 

```
[2021-10-05 23:35:19,468] INFO: Creating {'project': 'CQ', 'labels': ['upstream'], 'issue_updates': ['title', 'description', 'comments'], 'sync': ['issue'], 'jira_instance': 'omegaprime-jira'} issue for <Issue https://github.com/apache/camel-quarkus/issues/2957 >
[2021-10-05 23:35:19,468] INFO: Creating issue.
[2021-10-05 23:35:19,881] ERROR:    Failed on <Issue https://github.com/apache/camel-quarkus/issues/2957 >
[2021-10-05 23:35:22,833] ERROR: Exception on /handle-event [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/src/sync2jira/sync-page/event-handler.py", line 36, in handle_event
    initialize_issues(config, repo_name=repo_name)
  File "/usr/local/lib/python3.9/site-packages/sync2jira/main.py", line 220, in initialize_issues
    d_issue.sync_with_jira(issue, config)
  File "/usr/local/lib/python3.9/site-packages/sync2jira/downstream_issue.py", line 1303, in sync_with_jira
    _create_jira_issue(client, issue, config)
  File "/usr/local/lib/python3.9/site-packages/sync2jira/downstream_issue.py", line 623, in _create_jira_issue
    downstream = client.create_issue(**kwargs)
  File "/usr/lib/python3.9/site-packages/jira/client.py", line 1110, in create_issue
    r = self._session.post(url, data=json.dumps(data))
  File "/usr/lib/python3.9/site-packages/jira/resilientsession.py", line 154, in post
    return self.__verb('POST', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/jira/resilientsession.py", line 147, in __verb
    raise_on_error(response, verb=verb, **kwargs)
  File "/usr/lib/python3.9/site-packages/jira/resilientsession.py", line 56, in raise_on_error
    raise JIRAError(
jira.exceptions.JIRAError: JiraError HTTP 400 url: https://issues.redhat.com/rest/api/2/issue
	text: The entered text is too long. It exceeds the allowed limit of 65,534 characters.
	
	response headers = {'x-arequestid': '1415x2984621x2', 'x-asessionid': 'ikyvns', 'x-anodeid': 'rh1-jira-prod-2', 'referrer-policy': 'strict-origin-when-cross-origin', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'Content-Security-Policy': "frame-ancestors 'self'", 'strict-transport-security': 'max-age=31536000', 'x-seraph-loginreason': 'OK', 'x-ausername': 'upstream-sync', 'Content-Encoding': 'gzip', 'Vary': 'User-Agent, Accept-Encoding', 'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '136', 'Expires': 'Tue, 05 Oct 2021 23:35:19 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Tue, 05 Oct 2021 23:35:19 GMT', 'Connection': 'close', 'x-rh-edge-request-id': 'a431851b', 'x-rh-edge-reference-id': '0.573c4317.1633476919.a431851b', 'x-rh-edge-cache-status': 'Miss from child, Miss from parent'}
	response text = {"errorMessages":[],"errors":{"description":"The entered text is too long. It exceeds the allowed limit of 65,534 characters."}}
[2021-10-05 23:35:22,834] INFO: 172.28.2.1 - - [05/Oct/2021 23:35:22] "[35m[1mPOST /handle-event HTTP/1.1[0m" 500 -
```

the culprit according to the error log is this GH issue - https://github.com/apache/camel-quarkus/issues/2957
It's first comment exceeds 180K characters

**Comment by sidpremkumar** [comment]
@qgong lets try that. I believe that issue you linked also has a large content so I added a check for that as well. Please see here:  https://github.com/release-engineering/Sync2Jira/pull/125
